### ISSUE TITLE
Example RBAC Role to only allow k6 tests with k6-operator

### ISSUE THREAD

**Issue by jsclifford** [grafana/k6-operator#109]
I am trying to grant users in my cluster access to run k6 tests with the k6-operator.  I want to use least privilege.  The users job is to only run load/stress tests.  Can someone provide an example of a kubernetes role that grants the minimal permissions in order to run a k6 test?

**Comment by jsclifford** [comment]
Found out the readme provides permissions in the cronjob section.

**Comment by yorugac** [comment]
@jsclifford Thanks for combing back with the update!
