### ISSUE TITLE
k6 operator is not creating the jobs, when k6 manifest applied to k8s.

### ISSUE THREAD

**Issue by surajmachamasi** [grafana/k6-operator#110]
the operator logs after deploying the k6 kind in k8s.  no jobs is created, no pod is created. 
        
        2022-05-19T04:34:44.078Z	ERROR	controller	Reconciler error	{"reconcilerGroup": "k6.io", "reconcilerKind": "K6", "controller": "k6", "name": "k6-sample", "namespace": "default", "error": "K6.k6.io \"k6-sample\" is invalid: status.stage: Unsupported value: \"initialization\": supported values: \"created\", \"started\", \"finished\""}
          github.com/go-logr/zapr.(*zapLogger).Error

**Comment by codedesignplus** [comment]
Hi every one. 

The operator failed to change status to initialization with version operator:latest

**Exception**: 
K6.k6.io "ak6-116258" is invalid: status.stage: Unsupported value: "initialization": supported values: "created", "started" 

`
2022-05-23T15:25:01.723Z    ERROR    controllers.K6    Could not update status of custom resource    
{
      "k6": "load-testing/ak6-116258", 
      "error": "K6.k6.io \"ak6-116258\" is invalid: status.stage: Unsupported value: \"initialization\": supported values: \"created\", \"started\""
}
github.com/go-logr/zapr.(*zapLogger).Error
`

`
2022-05-23T15:25:01.723Z    ERROR    controller    Reconciler error    
{
        "reconcilerGroup": "k6.io", 
        "reconcilerKind": "K6", 
        "controller": "k6",
        "name": "ak6-116258", 
        "namespace": "load-testing", 
        "error": "K6.k6.io \"ak6-116258\" is invalid: status.stage: Unsupported value: \"initialization\": supported values: \"created\", \"started\""
}
github.com/go-logr/zapr.(*zapLogger).Error
`

**Stack Trace:**

2022-05-23T15:25:01.712Z    INFO    controllers.K6    Initialize test    {"k6": "load-testing/ak6-116258"}
2022-05-23T15:25:01.712Z    INFO    controllers.K6    Changing stage of K6 status to initialization    {"k6": "load-testing/ak6-116258"}
2022-05-23T15:25:01.723Z    ERROR    controllers.K6    Could not update status of custom resource    {"k6": "load-testing/ak6-116258", "error": "K6.k6.io \"ak6-116258\" is invalid: status.stage: Unsupported value: \"initialization\": supported values: \"created\", \"started\""}
github.com/go-logr/zapr.(*zapLogger).Error
    /go/pkg/mod/github.com/go-logr/zapr@v0.1.0/zapr.go:128
github.com/grafana/k6-operator/controllers.InitializeJobs
    /workspace/controllers/k6_initialize.go:41
github.com/grafana/k6-operator/controllers.(*K6Reconciler).Reconcile
    /workspace/controllers/k6_controller.go:63
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler
    /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.6.2/pkg/internal/controller/controller.go:235
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
    /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.6.2/pkg/internal/controller/controller.go:209
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).worker
    /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.6.2/pkg/internal/controller/controller.go:188
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1
    /go/pkg/mod/k8s.io/apimachinery@v0.18.6/pkg/util/wait/wait.go:155
k8s.io/apimachinery/pkg/util/wait.BackoffUntil
    /go/pkg/mod/k8s.io/apimachinery@v0.18.6/pkg/util/wait/wait.go:156
k8s.io/apimachinery/pkg/util/wait.JitterUntil
    /go/pkg/mod/k8s.io/apimachinery@v0.18.6/pkg/util/wait/wait.go:133
k8s.io/apimachinery/pkg/util/wait.Until
    /go/pkg/mod/k8s.io/apimachinery@v0.18.6/pkg/util/wait/wait.go:90
2022-05-23T15:25:01.723Z    ERROR    controller    Reconciler error    {"reconcilerGroup": "k6.io", "reconcilerKind": "K6", "controller": "k6", "name": "ak6-116258", "namespace": "load-testing", "error": "K6.k6.io \"ak6-116258\" is invalid: status.stage: Unsupported value: \"initialization\": supported values: \"created\", \"started\""}
github.com/go-logr/zapr.(*zapLogger).Error
    /go/pkg/mod/github.com/go-logr/zapr@v0.1.0/zapr.go:128
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler
    /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.6.2/pkg/internal/controller/controller.go:237
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
    /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.6.2/pkg/internal/controller/controller.go:209
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).worker
    /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.6.2/pkg/internal/controller/controller.go:188
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1
    /go/pkg/mod/k8s.io/apimachinery@v0.18.6/pkg/util/wait/wait.go:155
k8s.io/apimachinery/pkg/util/wait.BackoffUntil
    /go/pkg/mod/k8s.io/apimachinery@v0.18.6/pkg/util/wait/wait.go:156
k8s.io/apimachinery/pkg/util/wait.JitterUntil
    /go/pkg/mod/k8s.io/apimachinery@v0.18.6/pkg/util/wait/wait.go:133
k8s.io/apimachinery/pkg/util/wait.Until
    /go/pkg/mod/k8s.io/apimachinery@v0.18.6/pkg/util/wait/wait.go:90

**Comment by codedesignplus** [comment]
Hi every one. 
Sorry, my English is not very good but the following steps are a temporary solution

I checked the version the controller in the next link https://github.com/grafana/k6-operator/pkgs/container/operator and I changed the versión to **ghcr.io/grafana/operator:controller-v0.0.7rc3** in  the deploy k6-operator-controller-manager. 

![image](https://user-images.githubusercontent.com/73084334/169864215-61529225-6a3f-40af-bd33-14ea30120e51.png)

**Comment by guillermotti** [comment]
Hello! I fix this issue changing the K6 CRD. The CRD is now including [two more states](https://github.com/grafana/k6-operator/commit/53de235c36edb29e8c408e23856e166116386238#diff-57c5b8bf12127fb33a0cffad3848f4049c0c3cdbb03119fcb0c17524affa11faR1959-R1960) `initialization` and `initializated`.

Adding those states to the CRD `k6s.k6.io` fix the issue.

**Comment by yorugac** [comment]
Hi @surajmachamasi Thanks for opening the issue!

@guillermotti is right: there were new states added in the last version in order to support more complex logic, so the definition must be re-deployed. Thanks for responding :slightly_smiling_face:

**Comment by cdanmar** [comment]
It appears that this change ground our tests to a halt today. Changing the image helped, but what is the long term fix? Do we need to re-install the operator to use future versions?

**Comment by yorugac** [comment]
Hi @cdanmar, yes, for this update you'll need to re-install CRD for sure. I've added a warning note about it to the release notes here:
https://github.com/grafana/k6-operator/releases/tag/v0.0.7

I don't think there is another way to add the kind of changes as in this release... at least nothing that won't be far more cumbersome than simply updating CRD. E.g. it's not feasible to support pre-v0.0.7 and v0.0.7 CRDs at the same time.

k6-operator is at the development stage when CRD itself is still being updated rather often but in most cases so far those changes were pure additions and you were free ignore them if you didn't need that particular addition. But this time the change of CRD was more complicated so it has to be updated. IMHO, it's a good practice to update CRD together with image each time: we don't keep a compatibility table of versions after all, i.e. how would one know which version works with which CRD? I realize this update created trouble with the update so perhaps, it makes sense to start adding the "how to update" to release notes or just add to the README... If there are any ideas on improving the release process to make it smoother for everyone, I'll be happy to hear it :slightly_smiling_face:

**Comment by saad1200** [comment]
@yorugac Would you please explain what do you mean by re-installing CRD my be done with update togather with the image? what image?
I have re-installed the K6 operator to use the latest release but for some reason I started seeing other problems like 
- __ENV variables are undefined 

Any idea why does this happen?

Thank you

**Comment by yorugac** [comment]
Hi @saad1200, this sounds like something in the setup of your test itself. Environment vars must be passed in the yaml -- I'd start with re-checking that. Also, please ask such questions in the community forum. This issue remained open to gather potential feedback on version policies. I'll probably close it now.
