### ISSUE TITLE
prometheus cant scrape the metrics from the job

### ISSUE THREAD

**Issue by ranyhb** [grafana/k6-operator#114]
hi,
after a job is completed you cant scrape the metrics from the job. so the soultion of exporting the metrics for the prometheus using the pod monitor isn't a good solution. 
i would like to hear from you how to solve this problem.
regards,
rani

**Comment by yorugac** [comment]
Hi @ranyhb,
Are you using https://github.com/szkiba/xk6-prometheus for metrics? You're right, the pull-based approach is not very suitable for operator. Instead, it makes sense to switch to push-based approach with PRW extension:
https://github.com/grafana/xk6-output-prometheus-remote
With it, k6 will exit only after pushing the metrics to Prometheus.

**Comment by yorugac** [comment]
> maybe we should udpate the ReadMe file to refence the https://github.com/grafana/xk6-output-prometheus-remote extension instead of the https://github.com/szkiba/xk6-prometheus.

Yes, for sure! I believe it was even planned once but then forgotten :sweat_smile:
