### ISSUE TITLE
How to aggregate the metrics for single test which runs parallelly

### ISSUE THREAD

**Issue by amitkpal83** [grafana/k6-operator#115]
Hi All,

I need help how to aggregate the metrics for single test which runs parallelly in K8. I want to fail the jenkins pipeline if threshold failed. I know we cannot do this straight forward so I am thinking to push all the metrics into influxdb then aggregate the metrics and call hook in jenkins pipeline to pass the job or fail based on the threshold. Can we add any custom id field in K6 response to influxdb which can tell multiple metrics are part of single test? 

Or any similar kind of approach if somebody has used?

Regards,
Amit

**Comment by yorugac** [comment]
I believe this was answered in the community [forum question](https://community.k6.io/t/k6-operator-how-to-aggregate-the-metrics-for-single-test-which-runs-parallelly/3853). Please close the issue if so :slightly_smiling_face:
