### ISSUE TITLE
Sent the metrics in InfluxDb

### ISSUE THREAD

**Issue by amitkpal83** [grafana/k6-operator#116]
Hi All,

As given in the example we can sent the metrics to kafka "arguments: --out kafka=brokers=kafka-host:9092,topic=test-output,format=json". Can we have similar for influxdb, if yes please tell the proper arguments for the same like we have for kafka?

**Comment by yorugac** [comment]
Hi @amitkpal83,
Yes, any k6 extension can be used in the same way. Please see https://k6.io/docs/extensions/ for the full list of extensions. Specifically InfluxDB v1 is [supported natively in k6](https://k6.io/docs/results-visualization/influxdb-+-grafana/), while v2 is among extensions.

**Comment by amitkpal83** [comment]
Hi @yorugac

Thanks for responding. I hope below is the correct syntax for V1.
arguments: --out K6_INFLUXDB_USERNAME=xxx,K6_INFLUXDB_PASSWORD=xxx,influxdb=xxx

**Comment by yorugac** [comment]
`K6_INFLUXDB_USERNAME` and `K6_INFLUX_PASSWORD` are environment variables, I believe, not arguments. Only `--out influxdb=...` is an argument.

**Comment by yorugac** [comment]
It seems this question was answered so I'm closing this issue. Re-open it if needed.
