### ISSUE TITLE
error : unknown flag: --execution-requirements

### ISSUE THREAD

**Issue by joeunlog** [grafana/k6-operator#127]
I setup k6-operator at my eks cluster.
It was working fine until about a week ago.
Today, when I created k6 and tried to test it, an error stating "unknown flag: --execution-requirements" occurred in the k6 initializer.
I don't know the cause at all. How should I check the operation?

![image](https://user-images.githubusercontent.com/78069372/177261201-79c848ea-301b-4f42-aaf3-07f773f91870.png)
![image](https://user-images.githubusercontent.com/78069372/177261316-d128f471-a2aa-4fa8-ba03-335c83eee9d1.png)
![image](https://user-images.githubusercontent.com/78069372/177261251-92fa41a7-e055-4af5-b107-374ac2556d90.png)

**Comment by yorugac** [comment]
Hi @joeunlog, are you using custom image for runner? If so, what version of k6 are you using to build it?

**Comment by joeunlog** [comment]
![image](https://user-images.githubusercontent.com/78069372/177262590-fa97e784-a321-42b9-ae27-9148a824e847.png)
![image](https://user-images.githubusercontent.com/78069372/177262622-a96cdc7e-6c37-432b-b71c-36dee503b970.png)
I use `latest` tag, so I don't know specific version.

**Comment by joeunlog** [comment]
![image](https://user-images.githubusercontent.com/78069372/177263807-257d2cf9-51ed-4fc6-a3c7-b12889dac01a.png)

@yorugac Since I made an image when installing k6, I think you can refer to the captured version of k6.

**Comment by yorugac** [comment]
I think `latest` caused issues with cached versions just recently :thinking: Could you please build with a tag instead? So use the following to build your custom image:
```
FROM ghcr.io/grafana/operator:runner-v0.0.8rc1
...
```
`v0.0.8rc1` was made just yesterday.

**Comment by joeunlog** [comment]
![image](https://user-images.githubusercontent.com/78069372/177266514-a47a7920-6337-4e20-a4fe-35faf2de7b70.png)
![image](https://user-images.githubusercontent.com/78069372/177266563-87e8cc7f-9e9e-4235-acb6-499ed39c5af7.png)

Same error occurred.
And, I tested grafana/k6:latest image as runner, it work fine. Could it be that xk6 build is the cause?

**Comment by yorugac** [comment]
I think I've found the problem. That xk6 extension wasn't updated in awhile and it uses k6 0.32:
https://github.com/szkiba/xk6-prometheus/blob/b3eaefdbaa7f518d8186b934b10a26e7e3aceeeb/go.mod#L9

That version won't work with the operator anymore. Did you see that extension in Readme? We should update it - it came up before, in #114.

Please switch to using one of our officially supported extensions, i.e. the ones hosted at `https://github.com/grafana`.
Alternatively, Ivan Szkiba might be happy with the PR to his extension too :slightly_smiling_face:

**Comment by joeunlog** [comment]
@yorugac I checked xk6 officially supported extensions, but couldn't find proper extension.
Could you recommand extension for using with prometheus-stack?
I use podmonitor for scraping k6 http reponse metric while testing.

I read (xk6-output-prometheus-remote)[https://github.com/grafana/xk6-output-prometheus-remote] but I couldn't attach to podmonitor.

**Comment by joeunlog** [comment]
I solved the problem by using ghcr.io/grafana/operator:controller-v0.0.7 image.
This is temporary action. I will continue to look for available extensions to use the latest version of go.
I will close this issue. Thanks for the quick response.

**Comment by prateek-pagaria** [comment]
@joeunlog @yorugac  I am still facing the issue. k6 pods are not getting created. I tried using ghcr.io/grafana/operator:controller-v0.0.7 image. This is Dockerfile that i created, as suggested above.

<img width="1440" alt="Screenshot 2022-07-07 at 10 56 12" src="https://user-images.githubusercontent.com/108855024/177698002-5d322bae-73a0-4e0c-89e3-a03e4b680531.png">

Pods not getting created. see below ss
<img width="1440" alt="Screenshot 2022-07-07 at 10 54 21" src="https://user-images.githubusercontent.com/108855024/177698164-c2bee212-182a-401c-877c-eaa98819fa83.png">

below is my k6 resource. pulling image which i pushed from my private repo
`apiVersion: k6.io/v1alpha1
kind: K6
metadata:
  name: k6-req-otp-constant-rate-testing
  namespace: perf-testing
spec:
  parallelism: 1
  script:
    configMap:
      name: npci-req-otp-flow
      file: req_otp.js
  arguments: --out prometheus=subsystem=k6 --insecure-skip-tls-verify
  ports:
    - containerPort: 5656
      name: metrics
  runner:
    image: us-central1-docker.pkg.dev/engineering-330305/governor-k8s-testing/k6-prometheus:0.0.1`

kindly assist.

**Comment by joeunlog** [comment]
@prateek-pagaria
I use ghcr.io/grafana/operator:controller-v0.0.7 image as a k6 operator controller. Not k6 extention image.
![image](https://user-images.githubusercontent.com/78069372/177699217-412761fb-160e-46f5-84cb-9f21853e480b.png)
This is my dockerfile.

You should use controller-v0.0.7 for k6-operator/controller.
![image](https://user-images.githubusercontent.com/78069372/177699370-7adf834c-f97b-4dbe-bf6f-44290973d71b.png)

**Comment by joeunlog** [comment]
@prateek-pagaria 
I think you should edit k6-operator-controller's container image

**Comment by yorugac** [comment]
@prateek-pagaria This issue is not because of controller - it is because of **k6 version** which is runner image. When you're building custom runner image of k6 with this specific extension (`https://github.com/szkiba/xk6-prometheus`), you're using outdated k6 libraries. Solution: do not use that extension until it is updated.

PS you didn't have to switch from forum to Github :slightly_smiling_face:
