### ISSUE TITLE
Documentation request: cleanup field of k6 CR spec usage

### ISSUE THREAD

**Issue by mugioka** [grafana/k6-operator#130]
https://github.com/grafana/k6-operator/blob/9db5af67a7d026664eac5b2879db2103c96443cc/controllers/k6_controller.go#L78-L81

It would be better to document the use of the cleanup field.

**Comment by javaducky** [comment]
This has been addressed with [#1251](https://github.com/grafana/k6-docs/pull/1251). Use of the [`cleanup` option has been highlighted as a "best practice"](https://k6.io/docs/testing-guides/running-distributed-tests/#run-your-test) if metrics are being published, i.e. you don't need to scrape logs after tests.
