### ISSUE TITLE
Publish image to Dockerhub

### ISSUE THREAD

**Issue by ghostsquad** [grafana/k6-operator#147]
This is a request to publish the image to dockerhub so that I don't need to build it locally.

**Comment by yorugac** [comment]
Hi @ghostsquad, you don't need to build it locally, you can use the Github package:
https://github.com/grafana/k6-operator/pkgs/container/operator
The `latest` there usually contains the latest commit on `main` branch.

**Comment by ghostsquad** [comment]
Oh thank you, I didn't realize that this was using using github packages to publish the images.
