### ISSUE TITLE
Add ImagePullPolicy option on the runner and starter specs

### ISSUE THREAD

**Issue by jfroment** [grafana/k6-operator#152]
### Feature Description

Would it be possible to add the field "imagePullPolicy" on the K6 CRD spec?
In our environment, we use custom images for both the runner images and the starter, these images containers extensions, internal tools, and certificates authorities to be able to communicate with the service we test.
But in order to ensure we always pull the latest image for a given tag, being able to set the imagePullPolicy to "always" would be a great plus.

**Comment by yorugac** [comment]
Hi @jfroment, please see #145 - I believe it's the same issue.

**Comment by jfroment** [comment]
Hi @yorugac , thanks for the quick answer!

If I'm not mistaken, the PR #145 is about ImagePullSecret while what I'm asking if for ImagePullPolicy, which is a different option. See the official documentation for more details. Basically it is a string with 3 possible options. The operator, by not specifying anything, sets it to "IfNotPresent" by default.

**Comment by yorugac** [comment]
@jfroment yes, you're right of course: I shouldn't have responded in a hurry :sweat_smile: Thank you for opening the issue!
