### ISSUE TITLE
Improve linting

### ISSUE THREAD

**Issue by yorugac** [grafana/k6-operator#157]
### Feature Description

Currently, k6-operator uses only `yaml-lint` for manifests. Add Golang linters.

### Suggested Solution (optional)

k6 repo can be used as a main reference.

**Comment by u5surf** [comment]
@yorugac  Hi, I'd like to work on this issue.
Can we use golangci-lint?

**Comment by yorugac** [comment]
@u5surf sure. As mentioned in description, k6 repo is the reference point - it uses golangci-lint.
