### ISSUE TITLE
Option threshold abortOnFail does not work with k6-operator

### ISSUE THREAD

**Issue by Slm0n87** [grafana/k6-operator#189]
### Brief summary

I wants to use the `abortOnFail: true` feature for a threshold to let K6 abort the test if my threshold was exceeded.  
The following K6 file 

### k6-operator version or image

gcr.io/kubebuilder/kube-rbac-proxy:v0.5.0,ghcr.io/grafana/operator:latest

### K6 YAML

configmap:
```
import http from 'k6/http';
import { check } from 'k6';
import { sleep } from "k6";

export const options = {
  stages: [
    { target: 200, duration: '1m' },
    { target: 0, duration: '30s' },
  ],
  thresholds: {
    http_req_duration: [{ threshold: 'p(95) < 500', abortOnFail: true }],
  },
};

export default function () {
  const result = http.get('https://test-api.k6.io/public/crocodiles/');
  check(result, {
    'http response status code is 200': result.status === 200,
  });
  sleep(0.1);
}
```
K6 Yaml:
```
apiVersion: k6.io/v1alpha1
kind: K6
metadata:
  name: k6-sample
spec:
  parallelism: 4
  separate: true
  script:
    configMap:
      name: crocodile-stress-test
      file: test_treshold.js
```

### Steps to reproduce the problem

Apply the test script, apply the configmap.

### Expected behaviour

test script should run at k8s same as tested locally by "k6 run <script>"

### Actual behaviour

k6-operator-controller-manager can not start the test.
Logs:

`manager }`    {"namespace": "k6", "name": "k6-sample", "error": "json: cannot unmarshal object into Go struct field InspectOutput.thresholds of type string"}                                            │
│ manager github.com/go-logr/zapr.(*zapLogger).Error                                                                                                                                                       │
│ manager     /go/pkg/mod/github.com/go-logr/zapr@v0.1.0/zapr.go:128                                                                                                                                       │
│ manager github.com/grafana/k6-operator/controllers.RunValidations                                                                                                                                        │
│ manager     /workspace/controllers/k6_initialize.go:137                                                                                                                                                  │
│ manager github.com/grafana/k6-operator/controllers.(*K6Reconciler).Reconcile                                                                                                                             │
│ manager     /workspace/controllers/k6_controller.go:75                                                                                                                                                   │
│ manager sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler                                                                                                            │
│ manager     /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.6.2/pkg/internal/controller/controller.go:235                                                                                                  │
│ manager sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem                                                                                                         │
│ manager     /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.6.2/pkg/internal/controller/controller.go:209                                                                                                  │
│ manager sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).worker                                                                                                                      │
│ manager     /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.6.2/pkg/internal/controller/controller.go:188                                                                                                  │
│ manager k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1                                                                                                                                             │
│ manager     /go/pkg/mod/k8s.io/apimachinery@v0.18.6/pkg/util/wait/wait.go:155                                                                                                                            │
│ manager k8s.io/apimachinery/pkg/util/wait.BackoffUntil                                                                                                                                                   │
│ manager     /go/pkg/mod/k8s.io/apimachinery@v0.18.6/pkg/util/wait/wait.go:156                                                                                                                            │
│ manager k8s.io/apimachinery/pkg/util/wait.JitterUntil                                                                                                                                                    │
│ manager     /go/pkg/mod/k8s.io/apimachinery@v0.18.6/pkg/util/wait/wait.go:133                                                                                                                            │
│ manager k8s.io/apimachinery/pkg/util/wait.Until                                                                                                                                                          │
│ manager     /go/pkg/mod/k8s.io/apimachinery@v0.18.6/pkg/util/wait/wait.go:90                                                                                                                             │
│ manager 2023-02-03T11:31:12.962Z    ERROR    controller    Reconciler error    {"reconcilerGroup": "k6.io", "reconcilerKind": "K6", "controller": "k6", "name": "k6-sample", "namespace": "k6", "error": │
│ manager github.com/go-logr/zapr.(*zapLogger).Error`

**Comment by yorugac** [comment]
Hi @Slm0n87, thank you for opening the issue. Actually, the fix for this was merged in just last week in #176 - please try the newest release of the operator.
