### ISSUE TITLE
Setup CI for development and production builds

### ISSUE THREAD

**Issue by simskij** [grafana/k6-operator#20]
Using GitHub Actions.

**Comment by KnechtionsCoding** [comment]
@simskij Do we know what CI Operations are wanted? Test, bundle, etc? Happy to write some github actions to help out

**Comment by dgzlopes** [comment]
I think that the biggest necessity right now (apart from #4) is building/pushing new Docker images on each release.

Right now this process is manual, and adds a bit of friction.

**Comment by simskij** [comment]
@KnechtionsCoding that would be great! Yeah, testing, bundling and pushing to ghcr would probably do. I'd be happy to set up any secrets needed (if any, not sure since it's all GH).

**Comment by KnechtionsCoding** [comment]
@simskij @dgzlopes Is that the `make bundle` command? I posted #28 when I tried to run it locally to see what the output was. 

I'll work on figuring out a GH action for the rest of these in the mean time.

**Comment by immavalls** [comment]
Adding the bundle generation on releases would indeed help users like https://community.k6.io/t/make-deploy-issue-from-controller-gen/5871/. We see some struggles building the operator when following https://k6.io/blog/running-distributed-tests-on-k8s/
