### ISSUE TITLE
Rename CRD fields to have standard naming

### ISSUE THREAD

**Issue by yorugac** [grafana/k6-operator#206]
k6-operator has a non-standard (in context of Kubernetes API) naming for node selector: it's `nodeselector` instead of `nodeSelector`. It's preferable to fix it though it might be a breaking change for some.

**Comment by yorugac** [comment]
Together with renaming, consider using the type [`NodeSelector`](https://github.com/kubernetes/api/blob/v0.26.2/core/v1/types.go#L2798) instead of `map[string]string`.

**Comment by lplazas** [comment]
If this isn't assigned to anyone internally, I'd be happy to have it assigned to me.

**Comment by JorTurFer** [comment]
I have drafted a PR fixing this
