### ISSUE TITLE
Question: How does this project split rate between pods?

### ISSUE THREAD

**Issue by ostrovanka** [grafana/k6-operator#209]
Hello, team!

I have the following question:
looking at the example test you are running, looks like it is using a `ramping-vus` executor.
The project splits number of VUs based on the parallelizm value. E.g. paralellizm=4 => 50 VUs per pod

But does it has a built it logic for handling executors of `constant-arrival-rate` and zramping-arrival-rate` type? Will it split target rates too?

Thanks in advance for the answer and for this wonderful project you created!

**Comment by yorugac** [comment]
Hi @ostrovanka :wave: Yes, the logic is the same for any executor of k6. k6 Operator is not implementing any distribution on its own, it just utilizes methods already existing in k6, specifically [execution segment options](https://k6.io/docs/using-k6/k6-options/reference/#execution-segment). The splitting is equal between all runners. I believe a similar question was brought up here before: https://github.com/grafana/k6-operator/issues/120

Hope that answers the question!

**Comment by yorugac** [comment]
Closing as this seems to be resolved. Please feel free to re-open if needs be.
