### ISSUE TITLE
Assigning runner's security context to k6 initializer

### ISSUE THREAD

**Issue by mohamediag** [grafana/k6-operator#210]
### Feature Description

We would need to define `securityContext` on all pods created by K6 operator as per security requirement , but currently the `initializer` doesn't provide an option to do it.

**Comment by yorugac** [comment]
Hi @mohamediag, thanks for opening the issue! One way to resolve this is in the PR https://github.com/grafana/k6-operator/pull/175 - with it, you should be able to explicitly specify initializer spec separately from the runner. 

But it might also be good to consider adding security context assigned in initializer definition by default: similarly to how its done in the [runner definition](https://github.com/grafana/k6-operator/blob/151472705d2e35d1c6d9158affed2ab127c305ba/pkg/resources/jobs/runner.go#L152).

**Comment by mohamediag** [comment]
Hi @yorugac , seems the first PR is not being looked for a while, therefore the second option is fine for me as it seems quick to implement.

Shall a raise a PR for it if the repo is open for external contributor or can someone do it?

**Comment by mohamediag** [comment]
PR opened : https://github.com/grafana/k6-operator/pull/215

**Comment by mohamediag** [comment]
Hi @yorugac any idea when the PR can be reviewed and merged?

**Comment by yorugac** [comment]
Closed by #215
