### ISSUE TITLE
Rename K6 CRD to TestRun

### ISSUE THREAD

**Issue by yorugac** [grafana/k6-operator#226]
In order to improve readability of our interfaces, we should rename the K6 CRD from:
```
kind: K6
```
To:
```
kind: TestRun
```

Why? `kind: K6` is not very descriptive as from the first glance, it might mean a lot of things. If we add new CRDs (see #191), we should try to remove the confusing names as well.

This is a breaking change for existing setups so consider supporting both names for some period of time.

**Comment by yorugac** [comment]
`TestRun` CRD has been added as a duplicate of `K6` CRD with the latter being marked as deprecated in #286 
Missing dependency: #273 

We'll support both `K6` and `TestRun` for some time, to give people the opportunity to switch. But afterwards `K6` will be removed. IOW, we didn't get to the "breaking" part yet.

I'm leaving this issue open for now. What is left: 
- [ ] updating documentation
- [ ] removing `K6` CRD in the future™

**Comment by yorugac** [comment]
`K6` CRD is removed in `main` branch (i.e. the next release) so closing this issue 🎉

**Comment by jeromeguillaume** [comment]
Not sure if it's related to this change but (on January 24, 2024) the K6s operator doesn't work (looping restart) and it complains about following error:
`ERROR	controller-runtime.source.EventHandler	if kind is a CRD, it should be installed before calling Start	{"kind": "K6.k6.io", "error": "no matches for kind \"K6\" in version \"k6.io/v1alpha1\""}`

The image is: `ghcr.io/grafana/k6-operator:latest`

**Comment by yorugac** [comment]
Hi @jeromeguillaume, yes, absolutely, it's related. `K6` has had a deprecation warning for more than a year, now it's fully removed and the `latest` will not work with it. The same goes to all future releases of k6-operator. Please switch to using `TestRun`. It's a one-line change, the API is exactly the same 🙂

**Comment by yorugac** [comment]
@jeromeguillaume, that's very strange: v0.0.18 contains both `TestRun` and `K6` still. There was no release yet with this removal. At the moment, only `latest` image and kustomize setup contain the removal. 🤔 I guess this could happen if you're using the older installation that contains `K6` CRD with the `latest` image: that'd break indeed.

How are you installing / upgrading k6-operator?

**Comment by yorugac** [comment]
The [v0.0.19 release](https://github.com/grafana/k6-operator/releases/tag/v0.0.19) is the first one that contains this change fully: bundle, Helm chart and `latest` images were all updated.
