### ISSUE TITLE
k6-operator test runs don't propagate maxMetricSamplesPerPackage setting

### ISSUE THREAD

**Issue by esquonk** [grafana/k6-operator#228]
### Brief summary

Slack thread:
https://raintank-corp.slack.com/archives/C043CAPGCUR/p1683531983983669

ingest-api cloud service returns a config from create_test endpoint which includes maxMetricSamplesPerPackage setting among other things. These setting should be propagated to k6 instances so that it interacts with cloud output correctly.

One effect of this is that cloud ingest api gets larger-than-expected metrics packets that it cannot handle.

### k6-operator version or image

v0.0.9 

### K6 YAML

- "not available"

### Steps to reproduce the problem

Run a heavy test that generates lots of metric samples.

### Expected behaviour

Ingest packets are limited to maxMetricSamplesPerPackage.

### Actual behaviour

Ingest packets are not limited to maxMetricSamplesPerPackage.

**Comment by yorugac** [comment]
This is considered resolved with PR #229
