### ISSUE TITLE
Got `No active Subscription supports k6 CLI output to k6 Cloud with thresholds processing` but that works fine when run from k6 cli outside the operator

### ISSUE THREAD

**Issue by lorenzourb** [grafana/k6-operator#263]
### Brief summary

Using the k6-operator to trigger the tests had to build a custom image due to https://github.com/grafana/k6-operator/blob/main/pkg/cloud/cloud_output.go#L62 hard coded to True. It works when I set that to false but I lose the threshold processing in the cloud report.

The subscription I'm using definitely allows that as it works if I run a k6 script passing the --put cloud arg outside the operator.

### k6-operator version or image

0.0.10-rc2

### K6 YAML

building from the k6-operator code

### Steps to reproduce the problem

run a test in the k6-operator with --out cloud and a valid k6_cloud_token

### Expected behaviour

test should run, output and thresholds calculated

### Actual behaviour

`ERROR controllers.K6 Failed to create a new cloud test run."error": "(403/E2) Validation failed\n No active Subscription supports k6 CLI output to k6 Cloud with thresholds processing"}`

**Comment by yorugac** [comment]
Hi @lorenzourb, subscription for k6-operator is separate from "general" k6 subscription. Please write to [k6 support](https://k6.io/contact/) about this issue.
