### ISSUE TITLE
Avoid using "latest" in the image version deployed

### ISSUE THREAD

**Issue by rgordill** [grafana/k6-operator#301]
### Brief summary

When using "latest", any image that replaces this tag and has any backward compatibility issue like the one in the CRD ([controller-v0.0.11rc3](https://github.com/orgs/grafana/packages/container/k6-operator/133668563?tag=controller-v0.0.11rc3)) committed yesterday breaks the operator running.

Best practices says the sha256 id should be used instead of tags to avoid  TOCTOU (see [this article](https://sysdig.com/blog/toctou-tag-mutability) for example) 

### k6-operator version or image

controller-v0.0.11rc3

### K6 YAML

---

### Steps to reproduce the problem

Git checkout with a former branch (up to controller-v0.0.11rc3)

### Expected behaviour

Operator image consistent with the tag used in github to be deployed

### Actual behaviour

"Last" image deployed.

**Comment by yorugac** [comment]
Hi @rgordill, thank you for the issue. Could you please clarify, which method do you use to install the k6-operator?

We've recently added support for 2 modes of installation (bundle and Helm), neither of which should be using `latest` by default.

**Comment by rgordill** [comment]
I was using the "make install", as it was the traditional approach. Thanks for the tips, I would use from now on any of the other two approaches.
