### ISSUE TITLE
Integration with CI jobs: test trigger without need to delete existing custom resource 

### ISSUE THREAD

**Issue by DAT-Amundi** [grafana/k6-operator#312]
### Feature Description

Recreate test jobs and resources without need to delete the existing Custom resource, only synchronize should be able to relaunch tests , in order to automatize load tests 

### Suggested Solution (optional)

Run with : kubectl apply  -f .. 
without need to : kubectl delete -f 
I tried applying custom annotation and didn't work : 
spec:
  runner:
    metadata:
      annotations:
        deploymentTime:

**Comment by yorugac** [comment]
Hi @DAT-Amundi, thanks for the issue! It sounds to be very similar to edits of custom resource? This one: #305 
Could you please clarify the difference?

**Comment by DAT-Amundi** [comment]
Hi @yorugac thanks for your comment, the purpose of this issue is so precise, not sure it is covered by #305 , the main difference that here I want to relaunch the test even without any modification in the TestRun CRD, whenever I want to rerun tests it should be possible just by synchronizing

**Comment by yorugac** [comment]
@DAT-Amundi, in that case, I'm confused what do you mean by "synchronizing"? You mention ArgoCD: do you mean sync operation there? Then yes, changing annotation won't work as a "relaunch": from perspective of the k6-operator by adding annotation you *edited* TestRun CRD (with the help of ArgoCD) but as mentioned in #305, edits are not supported at the moment at all.
