### ISSUE TITLE
Export test metrics to Prometheus  

### ISSUE THREAD

**Issue by DAT-Amundi** [grafana/k6-operator#321]
As described in the Send test metrics to a remote write endpoint section [here](https://k6.io/docs/results-output/real-time/prometheus-remote-write/#send-test-metrics-to-a-remote-write-endpoint), we need to run k6 script with the --out flag and define the Prom endpoint url. 
I don't see how to do it in the helm chart, no related keys are defined in the CRD. 
Surely we don't have control to add the flag in the k6 run command. 
Is this feature configurable in the chart ? If yes how ? otherwise can it be planned for next release?

Thanks and regards

**Comment by yorugac** [comment]
It's all part of CRD: arguments and env vars for k6 are configured per TestRun. You can check these sections in Readme for examples:
- https://github.com/grafana/k6-operator/blob/main/README.md#using-extensions → `arguments` field
- https://github.com/grafana/k6-operator/blob/main/README.md#k6-cloud-output → `runner.env` field

TBH, this question looks more suitable for the forum :slightly_smiling_face:
