### ISSUE TITLE
Helm chart: ServiceMonitor namespace is not templated (system)

### ISSUE THREAD

**Issue by fculpo** [grafana/k6-operator#324]
Trying to install k6-operator via Helm and prometheus.enabled=true raises an error about "namespace system not found".
Inspecting the helm files, serviceMonitor.yaml has an hardcodded value for the ServiceMonitor namespace.

https://github.com/grafana/k6-operator/blame/0c3bf71105f8ce298a9801c436841802a5995545/charts/k6-operator/templates/prometheus/serviceMonitor.yaml#L15

**Comment by yorugac** [comment]
Thanks for catching this and opening the issue, @fculpo!

Command to repeat:
```bash
helm install k6-operator grafana/k6-operator --set prometheus.enabled=true
```
This can actually be considered a bug. Since `system` is not created by Chart :disappointed:
