### ISSUE TITLE
Optional installation of CRDs

### ISSUE THREAD

**Issue by illrill** [grafana/k6-operator#341]
### Feature Description

Some users prefer to install and manage CRDs _outside_ of charts. This can help ensure CRDs (and CRs) remain installed even when the chart is uninstalled.

When CRDs are installed as part of the chart templates, it's common to wrap them around a toggle. See for example [cert-manager](https://github.com/cert-manager/cert-manager/blob/0e5f9c679d418d98b785e35889ca1b06a0f8f119/deploy/charts/cert-manager/values.yaml#L53) and [external-secrets](https://github.com/external-secrets/external-secrets/blob/431aef844ddb688cc49d2feaa05c7f6b2ac6db34/deploy/charts/external-secrets/values.yaml#L16C18-L16C18). 

### Suggested Solution (optional)

Add an `installCRDs` boolean helm value.

**Comment by yorugac** [comment]
Hi @illrill,

> This can help ensure CRDs (and CRs) remain installed even when the chart is uninstalled.

Thanks for pointing this use case out! I vaguely remember wondering if we'll need such a field in k6-operator Helm but had doubts about its usefullness :smile:

**Comment by yorugac** [comment]
For completeness sake; and in case it'll be needed to locate the problem.

With this change, it's now possible to run k6-operator without CRDs installed very easily (arguably, easier than before) and doing that will result in errors like this:
```
2023-11-23T15:05:06Z	ERROR	controller-runtime.source.EventHandler	failed to get informer from cache	{"error": "failed to get API group resources: unable to retrieve the complete list of server APIs: k6.io/v1alpha1: the server could not find the requested resource"}
```
It is an expected error in this case. Solution: make a full installation with CRDs included.

**Comment by illrill** [comment]
@yorugac thanks, that's valuable information (I was initially considering just installing `TestRun`) 👍 

If anyone is interested, this is how I handled CRD installation using kubectl, separately from the Helm release lifecycle.

```
helm template k6-operator grafana/k6-operator \
  --set k6-operator.installCRDs=true \
  | yq 'select(.kind == "CustomResourceDefinition")' \
  | kubectl apply --server-side --force-conflicts -f -
```
```
helm install k6-operator grafana/k6-operator \
  --set k6-operator.installCRDs=false
```
