### ISSUE TITLE
In crd the applicationName is Test T&T and the test does not executes

### ISSUE THREAD

**Issue by arpitaso** [grafana/k6-operator#354]
### Brief summary

the k6 test does not execute if there is a special character in the applicatiionName
example:
applicationName: Test T&T
but this one works applicationName: Test TandT

### k6-operator version or image

k6 v0.47.0 (go1.21.2, darwin/arm64)

### TestRun / PrivateLoadZone YAML

arguments: --tag test_id=556 --tag region=abc --tag provider=azure --tag
platform_name=aa --tag product_id=Test T&T --tag env=preprod --tag app=a

### Steps to reproduce the problem

the crd has --tag product_id=Test T&T which is a special symbol and the test does not execute

### Expected behaviour

The test should execute successfully

### Actual behaviour

The test is not executing successfully because the special character in applicationName: Test T&T is not being executed, ideally it should execute

**Comment by yorugac** [comment]
Hi @arpitaso, sorry for the delay.

Thanks for opening the issue. This looks like a duplicate for https://github.com/grafana/k6-operator/issues/211
So I'm closing this one; please upvote the #211 instead or comment there if you'd like to add additional details.
