### ISSUE TITLE
 help .. aggregated output way

### ISSUE THREAD

**Issue by KilJaeeun** [grafana/k6-operator#392]
Hello, I've come here because I couldn't find the way. I'm wondering if there's a way to get an aggregated output independently, without relying on external services like cloud or InfluxDB, using the k6 operator. Currently, pods based on parallelism are generating their own outputs.

**Comment by yorugac** [comment]
Hi @KilJaeeun, no, there isn't. Our official solution for aggregation is k6 Cloud (part of Grafana Cloud) while k6-operator is a Kubernetes orchestrator. I'd say even if some kind of aggregation becomes OSS, it's more likely to happen in k6-core and not in k6-operator:
https://github.com/grafana/k6/issues/140

k6 Cloud is the most seamless solution but you can indeed use other solutions as well, just as you mentioned.

**Comment by yorugac** [comment]
Closing the issue as out of scope for k6-operator
