### ISSUE TITLE
Bundle the build output as a single yaml file (pre-commit hook)

### ISSUE THREAD

**Issue by simskij** [grafana/k6-operator#4]
@dgzlopes made an excellent point about how adding a full deployment bundle to the repo would allow us to drop the `make` and `kustomize` pre-requisites for usage. Once this is done, the relevant documentation and articles on the k6 blog needs to be updated as well.

**Comment by KnechtionsCoding** [comment]
@simskij @dgzlopes Are you envisioning a https://pre-commit.com/ hook? Or does this make more sense as a github action that runs when merged to master and outputs a bundle? That way pre-commit doesn't have to be installed, and you don't have to rely on a human catching/running it.

**Comment by dgzlopes** [comment]
Hey! Thanks for taking a look at this. I kinda prefer the Github Actions approach :)

**Comment by simskij** [comment]
Yeah, GHA makes more sense to me as well.

**Comment by yorugac** [comment]
Relevant example of bundle: https://github.com/prometheus-operator/prometheus-operator
