### ISSUE TITLE
 k6-operator failed on ARM based cluster 

### ISSUE THREAD

**Issue by kadhamecha-conga** [grafana/k6-operator#425]
### Brief summary

hi team,

Can we please make image multiplatform?
k6 controller operator  failed to start and gived error for manager as below :

exec /manager: exec format error

thanks.

### k6 version

3.6.0

### OS

EKS ARM

### Steps to reproduce the problem

deploy k6-operator on ARM based instance.

### Expected behaviour

The container should start successfully and run our application.

### Actual behaviour

manager container failed to start on ARM based cluster

**Comment by yorugac** [comment]
Hi @kadhamecha-conga, ARM has been included into k6-operator recently, and the latest version containing it has been released only last week:
https://github.com/grafana/k6-operator/releases/tag/v0.0.15
Please switch to that.

**Comment by yorugac** [comment]
Closing the issue. If the issue persist with the latest version (v0.0.16), please add more detail!
