### ISSUE TITLE
Add values schema to the k6-operator helm chart

### ISSUE THREAD

**Issue by petar-cvit** [grafana/k6-operator#431]
### Feature Description

Hey, could we add the [values.schema.json](https://helm.sh/docs/topics/charts/#schema-files) to the helm chart? We are working on a [tool](https://github.com/cyclops-ui/cyclops) that renders UIs for helm charts based on their schema and would love to support the k6-operator chart as well.

### Suggested Solution (optional)

Add the values.schema.json to the chart. Initially, the schema can cover just the basic set of fields, so it is easier to maintain.

**Comment by yorugac** [comment]
Hi @petar-cvit, sounds great! Thanks for the issue. And if the schema can be used in your tool, then of course, we can add it.

The one thing that is worrying here is how to maintain this long-term :sweat_smile: I cannot promise additional commitment to maintaining this myself. Can I ask you, if the `values.schema.json` needs to be written by hand or there's another way? I.e. could this schema be generated somehow? I've just found this tool:
https://github.com/losisin/helm-values-schema-json
It seems to work with comment annotations... Would it be sufficient to update the schema file with CI?

I think it'd be "ideal" if it were possible to just re-generate the schema when someone makes a change to the Chart :thinking:

**Comment by petar-cvit** [comment]
Hey @yorugac, we did a similar thing with cerbos. Here is the PR adding a schema on their repo https://github.com/cerbos/cerbos/pull/2230/files

They used github.com/dadav/helm-schema to generate the schema from the values file based on the comments (the same way you described it). If you want, I can look into setting it up on your repo and open a PR

**Comment by yorugac** [comment]
@petar-cvit, yes, I think that'd be great! Make command to generate the schema that can be called then in CI :+1:
