### ISSUE TITLE
Helm Chart - Disable Leader Election if running Operator as a single Pod

### ISSUE THREAD

**Issue by hartman17** [grafana/k6-operator#462]
### Feature Description

When deploying the operator using Helm there is no configurable option to disable the leader election process. This should be disabled when running the operator as a single pod, there is no need to check for leader election in this state.

### Suggested Solution (optional)

There are a couple of ways to do this: 

Add Helm config to disable leader election if  `.Values.manager.replicas == 1` 

or 

Add a `.Values.manager.leaderelection`  and allow users to pass in true/false to disable if it's not needed.

**Comment by yorugac** [comment]
Solved in https://github.com/grafana/k6-operator/pull/463.
