### ISSUE TITLE
Add securityContext to pod spec in Helm chart

### ISSUE THREAD

**Issue by chrissnell** [grafana/k6-operator#466]
### Feature Description

Currently, the Helm chart allows for adding a container `securityContext` to the manager and kube-rbac-proxy containers.  We also need to add some things (like `fsGroup`) to the pod-level `securityContext`.   The chart does not provide any means to do that presently.

### Suggested Solution (optional)

This request asks for two things:

1. a new configuration variable, `global.podSecurirtyPolicy`, which can be set to a pod-level `securityPolicy` object
2. an `if` conditional that triggers an inclusion of this variable in the `deployment.yaml` template [in the pod spec](https://github.com/grafana/k6-operator/blob/2fdcbb92ee9db433ade665c503955a111c967be9/charts/k6-operator/templates/deployment.yaml#L28).

**Comment by yorugac** [comment]
@chrissnell, I've just now noticed that you suggested a global variable: is there a specific reason for that? It is noticeable that `containerSecurityContext` is not global ATM.

**Comment by chrissnell** [comment]
> [@chrissnell](https://github.com/chrissnell), I've just now noticed that you suggested a global variable: is there a specific reason for that? It is noticeable that `containerSecurityContext` is not global ATM.

Indeed, global variable would be ideal for this use case if they applied to all containers.  I think most users that have requirements for security contexts will need them on _all_ pods, not just individuals.  Globals would make it easy to set it for everything.

**Comment by yorugac** [comment]
I see. Well, in case of k6-operator chart, there's only one deployment, with two containers. No subcharts, etc. So it seems to me there's little difference between configuration as `manager` variable and as `global` variable, except for UX becoming more confusing because of the clash with `manager.containerSecurityContext`.

**Comment by chrissnell** [comment]
> I see. Well, in case of k6-operator chart, there's only one deployment, with two containers. No subcharts, etc. So it seems to me there's little difference between configuration as `manager` variable and as `global` variable, except for UX becoming more confusing because of the clash with `manager.containerSecurityContext`.

There's also the tests themselves.   I wish that the images used for the tests could be set (globally) in the Helm chart.  It's unfortunate that k6-operator users have to add all of the security context stuff and other things like custom image registries in every single `TestRun` manifest.   It would be ideal if this could all be set globally, once, in the Helm chart values.

**Comment by yorugac** [comment]
>  I wish that the images used for the tests could be set (globally) in the Helm chart.

@chrissnell, thanks for the response! I kind of wondered if this might be the case here 😅 So this (propagating security setup from k6-operator deployment to the pods of the tests) is definitely a separate feature request. It needs a separate implementation as well: just global var in the chart won't achieve that (unless there is some Helm magic I'm not yet aware of; feel free to correct me if so). Furthermore, I'm not sure it's a good idea to add such a different behaviour just for Helm charts while omitting it in the app on its own.

Could I ask to create a separate issue for this? Smth like ~ TestRun pods should re-use `securityContext` and `containerSecurityContext` of k6-operator deployment by default.
