### ISSUE TITLE
 Too long: must have at most 1048576 bytes

### ISSUE THREAD

**Issue by Juandavi1** [grafana/k6-operator#61]
Hi guys, 

I am trying to create the configmap to save the test, but there seems to be a size limitation of 1Mb.

Do you know what other alternative can be implemented for this case?

Thanks a lot.

**Comment by KnechtionsCoding** [comment]
Support was added for a volume mount instead of configmap, I'd recommend you use that.

https://github.com/grafana/k6-operator/blob/main/api/v1alpha1/k6_types.go#L67

Instead of specifying configMap you should be able to specify volume mount, name and file to execute.

**Comment by Juandavi1** [comment]
Do you suddenly have an example?

**Comment by simskij** [comment]
What @KnechtionsCoding said. We should probably mention this limitation in the docs though. 👍🏽
