### ISSUE TITLE
"k6": executable file not found in $PATH: unknown

### ISSUE THREAD

**Issue by Juandavi1** [grafana/k6-operator#65]
Hi guys, 

We are trying to launch some tests but it seems that the starter cannot start. 

<img width="1636" alt="Captura de Pantalla 2021-08-17 a la(s) 2 08 34 a  m" src="https://user-images.githubusercontent.com/18731612/129680045-1118219c-764f-4995-b99a-e6eb31507f62.png">

I added k6 to the image and now we have another error

<img width="1231" alt="Captura de Pantalla 2021-08-17 a la(s) 2 12 02 a  m" src="https://user-images.githubusercontent.com/18731612/129680463-c2ecc79a-5268-4f7b-83a1-4cc0e4315c99.png">

Thanks

**Comment by dgzlopes** [comment]
Hi!

I think this should be fixed by https://github.com/grafana/k6-operator/pull/59

Do you mind trying again with those changes?

**Comment by Juandavi1** [comment]
Hello, thanks for answering.

I tried the change but the error keeps popping up. It is exactly the same scenario that they comment on here https://github.com/grafana/k6-operator/pull/59#issuecomment-89754686

this is my yaml

<img width="841" alt="Captura de Pantalla 2021-08-17 a la(s) 5 27 54 a  m" src="https://user-images.githubusercontent.com/18731612/129710273-7b24320e-1342-4e17-a1b3-2cbd97f4d993.png">

Do you know if I am missing other changes?

**Comment by dgzlopes** [comment]
I forgot to trigger the build of new Docker images!

Should work now :)
