### ISSUE TITLE
File permission when mounting from a PVC

### ISSUE THREAD

**Issue by cdanmar** [grafana/k6-operator#99]
Hello!

We are having some issues with mounting a test from a PVC we generated via a pipeline. We are mounting the volume like so:

```yaml
volumeClaim:
  name: file-mounting-test
  file: scratchpad-scratch.tar
```

I can see the test runners getting the file just fine, but they don't have permissions to open it:

```bash
time="2022-02-17T21:32:48Z" level=debug msg=Loading... moduleSpecifier="file:///test/scratchpad-scratch.tar" originalModuleSpecifier=/test/scratchpad-scratch.tar
time="2022-02-17T21:32:48Z" level=error msg="stat /test/scratchpad-scratch.tar: permission denied"
```
This happens because the test runners are running as user/group `12345:12345`, and PVC are mounted as root by Kubernetes by default. I was surprised to see nobody had this issue, or at least I could not find it here when searching.

Normally the fix in a kubernetes job would be pretty simple. You can set an fsGroup securityContext like so to make sure that when the volume gets mounted, it has the proper ownership:

```yaml
securityContext:
    fsGroup: 12345
```
I do not see a way to attach this to the k6 operator. Adding this to the job template would enable k6 runners to always mount files with the proper ownership.

This is currently a huge blocker for my team, and has us potentially seeking alternatives to load test data that are a lot hackier. Thanks to EKS and security restrictions, we don't have many sane alternatives for file mounting either.

**Comment by yorugac** [comment]
Hi @cdanmar
Thank you for opening the issue and sorry for a response delay! I think security context work from #74 / #101 should fit your use case: could you please confirm if that is so?

**Comment by yorugac** [comment]
Assuming this issue was resolved and can be closed. Please re-open as needs be.
